version: 2

project_name: monod

builds:
  - main: ./cmd/monod
    binary: monod
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=mono
      - -X github.com/cosmos/cosmos-sdk/version.AppName=monod
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  prerelease: auto
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
