// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monolythium/burn/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the burn module's genesis state.
type GenesisState struct {
	Params        Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Count         uint64                `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=total,proto3,customtype=cosmossdk.io/math.Int" json:"total"`
	AccountTotals []AccountBurnRecord   `protobuf:"bytes,4,rep,name=account_totals,json=accountTotals,proto3" json:"account_totals"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923dcbf7f11543b, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GenesisState) GetAccountTotals() []AccountBurnRecord {
	if m != nil {
		return m.AccountTotals
	}
	return nil
}

// AccountBurnRecord stores the cumulative burn total for a single account.
type AccountBurnRecord struct {
	Address string                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Total   cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total,proto3,customtype=cosmossdk.io/math.Int" json:"total"`
}

func (m *AccountBurnRecord) Reset()         { *m = AccountBurnRecord{} }
func (m *AccountBurnRecord) String() string { return proto.CompactTextString(m) }
func (*AccountBurnRecord) ProtoMessage()    {}
func (*AccountBurnRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923dcbf7f11543b, []int{1}
}
func (m *AccountBurnRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountBurnRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountBurnRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountBurnRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBurnRecord.Merge(m, src)
}
func (m *AccountBurnRecord) XXX_Size() int {
	return m.Size()
}
func (m *AccountBurnRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBurnRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBurnRecord proto.InternalMessageInfo

func (m *AccountBurnRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "monolythium.burn.v1.GenesisState")
	proto.RegisterType((*AccountBurnRecord)(nil), "monolythium.burn.v1.AccountBurnRecord")
}

func init() { proto.RegisterFile("monolythium/burn/v1/genesis.proto", fileDescriptor_5923dcbf7f11543b) }

var fileDescriptor_5923dcbf7f11543b = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0xe3, 0x7b, 0x7b, 0x2f, 0xaa, 0x0b, 0x48, 0x0d, 0x45, 0x0a, 0x45, 0x4a, 0x43, 0x07,
	0x14, 0x81, 0x6a, 0x2b, 0x65, 0x47, 0x6a, 0x16, 0xe8, 0x86, 0x52, 0x26, 0x96, 0xca, 0x49, 0xac,
	0xc4, 0xa2, 0xb1, 0xab, 0xd8, 0xa9, 0xe8, 0x2b, 0x30, 0xf1, 0x18, 0x8c, 0x0c, 0x7d, 0x88, 0x8e,
	0x55, 0x27, 0xc4, 0x50, 0xa1, 0x76, 0xe0, 0x25, 0x18, 0x50, 0x62, 0x23, 0x2a, 0xd1, 0xe9, 0x2e,
	0xd1, 0xf9, 0xf3, 0x3b, 0x27, 0xdf, 0xe7, 0x03, 0x9f, 0x15, 0x82, 0x8b, 0xc5, 0x5a, 0xe5, 0xac,
	0x2a, 0x70, 0x5c, 0x95, 0x1c, 0xaf, 0x02, 0x9c, 0x51, 0x4e, 0x25, 0x93, 0x68, 0x59, 0x0a, 0x25,
	0xec, 0x47, 0x67, 0x08, 0xaa, 0x11, 0xb4, 0x0a, 0xfa, 0x5d, 0x52, 0x30, 0x2e, 0x70, 0xf3, 0xd5,
	0x5c, 0xdf, 0x4d, 0x84, 0x2c, 0x84, 0xc4, 0x31, 0x91, 0x14, 0xaf, 0x82, 0x98, 0x2a, 0x12, 0xe0,
	0x44, 0x30, 0x6e, 0xfa, 0x4f, 0x74, 0x7f, 0xde, 0x64, 0x58, 0x27, 0xa6, 0xd5, 0xcb, 0x44, 0x26,
	0x74, 0xbd, 0x8e, 0x4c, 0xd5, 0xbb, 0xa4, 0x6d, 0x49, 0x4a, 0x52, 0x98, 0xb9, 0xe1, 0x6f, 0x00,
	0xef, 0xbf, 0xd1, 0x62, 0x67, 0x8a, 0x28, 0x6a, 0xbf, 0x86, 0xb7, 0x1a, 0x70, 0x80, 0x07, 0xfc,
	0xce, 0xf8, 0x29, 0xba, 0x20, 0x1e, 0xbd, 0x6b, 0x90, 0xb0, 0xbd, 0x3d, 0x0c, 0xac, 0xaf, 0xbf,
	0xbe, 0xbd, 0x00, 0x91, 0x99, 0xb2, 0x7b, 0xf0, 0x26, 0x11, 0x15, 0x57, 0xce, 0x95, 0x07, 0xfc,
	0x56, 0xa4, 0x13, 0x7b, 0x02, 0x6f, 0x94, 0x50, 0x64, 0xe1, 0x5c, 0x7b, 0xc0, 0x6f, 0x87, 0x2f,
	0xeb, 0xb9, 0x1f, 0x87, 0xc1, 0x63, 0xed, 0x41, 0xa6, 0x1f, 0x11, 0x13, 0xb8, 0x20, 0x2a, 0x47,
	0x53, 0xae, 0xf6, 0x9b, 0x11, 0x34, 0xe6, 0xa6, 0x5c, 0x45, 0x7a, 0xd2, 0x9e, 0xc1, 0x87, 0x24,
	0x69, 0xb6, 0xcd, 0x9b, 0x82, 0x74, 0x5a, 0xde, 0xb5, 0xdf, 0x19, 0x3f, 0xbf, 0x28, 0x70, 0xa2,
	0xd1, 0xb0, 0x2a, 0x79, 0x44, 0x13, 0x51, 0xa6, 0x61, 0xab, 0xfe, 0x67, 0xf4, 0xc0, 0xec, 0x78,
	0xdf, 0xac, 0x18, 0x7e, 0x06, 0xb0, 0xfb, 0x1f, 0x6a, 0x8f, 0xe1, 0x3d, 0x92, 0xa6, 0x25, 0x95,
	0xfa, 0x11, 0xda, 0xa1, 0xb3, 0xdf, 0x8c, 0x7a, 0x46, 0xd2, 0x44, 0x77, 0x66, 0xaa, 0x64, 0x3c,
	0x8b, 0xfe, 0x82, 0xff, 0x1c, 0x5e, 0xdd, 0xd5, 0x61, 0xf8, 0x76, 0x7b, 0x74, 0xc1, 0xee, 0xe8,
	0x82, 0x9f, 0x47, 0x17, 0x7c, 0x39, 0xb9, 0xd6, 0xee, 0xe4, 0x5a, 0xdf, 0x4f, 0xae, 0xf5, 0x01,
	0x65, 0x4c, 0xe5, 0x55, 0x8c, 0x12, 0x51, 0xe0, 0xf3, 0x93, 0xd6, 0xf1, 0x28, 0xc9, 0x09, 0xe3,
	0xf8, 0x93, 0xbe, 0xaf, 0x5a, 0x2f, 0xa9, 0x8c, 0x6f, 0x9b, 0xe3, 0xbe, 0xfa, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x98, 0xc3, 0x51, 0xb5, 0x9c, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountTotals) > 0 {
		for iNdEx := len(m.AccountTotals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountTotals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.Total.Size()
		i -= size
		if _, err := m.Total.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Count != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AccountBurnRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountBurnRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountBurnRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Total.Size()
		i -= size
		if _, err := m.Total.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Count != 0 {
		n += 1 + sovGenesis(uint64(m.Count))
	}
	l = m.Total.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.AccountTotals) > 0 {
		for _, e := range m.AccountTotals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *AccountBurnRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Total.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountTotals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountTotals = append(m.AccountTotals, AccountBurnRecord{})
			if err := m.AccountTotals[len(m.AccountTotals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountBurnRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountBurnRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountBurnRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
