// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monochain/burn/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryBurnStatsRequest struct {
}

func (m *QueryBurnStatsRequest) Reset()         { *m = QueryBurnStatsRequest{} }
func (m *QueryBurnStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBurnStatsRequest) ProtoMessage()    {}
func (*QueryBurnStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{2}
}
func (m *QueryBurnStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBurnStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBurnStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBurnStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBurnStatsRequest.Merge(m, src)
}
func (m *QueryBurnStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBurnStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBurnStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBurnStatsRequest proto.InternalMessageInfo

type QueryBurnStatsResponse struct {
	TotalBurns  uint64 `protobuf:"varint,1,opt,name=total_burns,json=totalBurns,proto3" json:"total_burns,omitempty"`
	TotalBurned string `protobuf:"bytes,2,opt,name=total_burned,json=totalBurned,proto3" json:"total_burned,omitempty"`
}

func (m *QueryBurnStatsResponse) Reset()         { *m = QueryBurnStatsResponse{} }
func (m *QueryBurnStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBurnStatsResponse) ProtoMessage()    {}
func (*QueryBurnStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{3}
}
func (m *QueryBurnStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBurnStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBurnStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBurnStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBurnStatsResponse.Merge(m, src)
}
func (m *QueryBurnStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBurnStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBurnStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBurnStatsResponse proto.InternalMessageInfo

func (m *QueryBurnStatsResponse) GetTotalBurns() uint64 {
	if m != nil {
		return m.TotalBurns
	}
	return 0
}

func (m *QueryBurnStatsResponse) GetTotalBurned() string {
	if m != nil {
		return m.TotalBurned
	}
	return ""
}

type QueryAccountBurnsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAccountBurnsRequest) Reset()         { *m = QueryAccountBurnsRequest{} }
func (m *QueryAccountBurnsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountBurnsRequest) ProtoMessage()    {}
func (*QueryAccountBurnsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{4}
}
func (m *QueryAccountBurnsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountBurnsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountBurnsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountBurnsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountBurnsRequest.Merge(m, src)
}
func (m *QueryAccountBurnsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountBurnsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountBurnsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountBurnsRequest proto.InternalMessageInfo

func (m *QueryAccountBurnsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAccountBurnsResponse struct {
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryAccountBurnsResponse) Reset()         { *m = QueryAccountBurnsResponse{} }
func (m *QueryAccountBurnsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountBurnsResponse) ProtoMessage()    {}
func (*QueryAccountBurnsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e22e82fe34b42f1, []int{5}
}
func (m *QueryAccountBurnsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountBurnsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountBurnsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountBurnsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountBurnsResponse.Merge(m, src)
}
func (m *QueryAccountBurnsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountBurnsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountBurnsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountBurnsResponse proto.InternalMessageInfo

func (m *QueryAccountBurnsResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "monochain.burn.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "monochain.burn.v1.QueryParamsResponse")
	proto.RegisterType((*QueryBurnStatsRequest)(nil), "monochain.burn.v1.QueryBurnStatsRequest")
	proto.RegisterType((*QueryBurnStatsResponse)(nil), "monochain.burn.v1.QueryBurnStatsResponse")
	proto.RegisterType((*QueryAccountBurnsRequest)(nil), "monochain.burn.v1.QueryAccountBurnsRequest")
	proto.RegisterType((*QueryAccountBurnsResponse)(nil), "monochain.burn.v1.QueryAccountBurnsResponse")
}

func init() { proto.RegisterFile("monochain/burn/v1/query.proto", fileDescriptor_0e22e82fe34b42f1) }

var fileDescriptor_0e22e82fe34b42f1 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xcf, 0x15, 0x08, 0xca, 0xa5, 0x4b, 0x8f, 0x52, 0x52, 0x0b, 0xdc, 0x62, 0xa9, 0x25, 0x14,
	0xea, 0x53, 0x5a, 0x06, 0x84, 0x18, 0x20, 0x13, 0x23, 0xb8, 0x1b, 0x42, 0x42, 0x67, 0xe7, 0xe4,
	0x58, 0x8a, 0xef, 0xb9, 0xbe, 0x73, 0x44, 0x84, 0x58, 0x58, 0x18, 0x41, 0xe2, 0x4b, 0x20, 0xb1,
	0xf0, 0x31, 0x3a, 0x16, 0xb1, 0x30, 0x21, 0x94, 0x20, 0xf1, 0x35, 0x90, 0xef, 0x8e, 0x40, 0x1b,
	0x47, 0xc9, 0x62, 0xdd, 0xbd, 0xf7, 0xfb, 0xe7, 0xf7, 0x6c, 0x7c, 0x23, 0x05, 0x01, 0x51, 0x9f,
	0x25, 0x82, 0x86, 0x45, 0x2e, 0xe8, 0xb0, 0x43, 0x8f, 0x0b, 0x9e, 0x8f, 0xfc, 0x2c, 0x07, 0x05,
	0x64, 0x6d, 0xda, 0xf6, 0xcb, 0xb6, 0x3f, 0xec, 0x38, 0x6b, 0x2c, 0x4d, 0x04, 0x50, 0xfd, 0x34,
	0x28, 0x67, 0x2f, 0x02, 0x99, 0x82, 0xa4, 0x21, 0x93, 0xdc, 0xd0, 0xe9, 0xb0, 0x13, 0x72, 0xc5,
	0x3a, 0x34, 0x63, 0x71, 0x22, 0x98, 0x4a, 0x40, 0x58, 0xec, 0x7a, 0x0c, 0x31, 0xe8, 0x23, 0x2d,
	0x4f, 0xb6, 0x7a, 0x3d, 0x06, 0x88, 0x07, 0x9c, 0xb2, 0x2c, 0xa1, 0x4c, 0x08, 0x50, 0x9a, 0x22,
	0x6d, 0xd7, 0x9d, 0x0d, 0x99, 0xb1, 0x9c, 0xa5, 0xb6, 0xef, 0xad, 0x63, 0xf2, 0xac, 0x74, 0x7d,
	0xaa, 0x8b, 0x01, 0x3f, 0x2e, 0xb8, 0x54, 0xde, 0x11, 0xbe, 0x72, 0xa6, 0x2a, 0x33, 0x10, 0x92,
	0x93, 0x87, 0xb8, 0x6e, 0xc8, 0x2d, 0xb4, 0x8d, 0xda, 0xcd, 0x83, 0x4d, 0x7f, 0xe6, 0x1d, 0x7d,
	0x43, 0xe9, 0x36, 0x4e, 0x7e, 0x6c, 0xd5, 0x3e, 0xfd, 0xfe, 0xb2, 0x87, 0x02, 0xcb, 0xf1, 0xae,
	0xe1, 0xab, 0x5a, 0xb4, 0x5b, 0xe4, 0xe2, 0x48, 0x31, 0x35, 0x75, 0x7b, 0x81, 0x37, 0xce, 0x37,
	0xac, 0xe1, 0x16, 0x6e, 0x2a, 0x50, 0x6c, 0xf0, 0xb2, 0x54, 0x37, 0xae, 0x17, 0x03, 0xac, 0x4b,
	0x25, 0x58, 0x92, 0x9b, 0x78, 0xf5, 0x1f, 0x80, 0xf7, 0x5a, 0x2b, 0xdb, 0xa8, 0xdd, 0x08, 0x9a,
	0x53, 0x04, 0xef, 0x79, 0xf7, 0x70, 0x4b, 0xab, 0x3f, 0x8e, 0x22, 0x28, 0x84, 0xd2, 0x3c, 0xeb,
	0x4c, 0x5a, 0xf8, 0x32, 0xeb, 0xf5, 0x72, 0x2e, 0x8d, 0x76, 0x23, 0xf8, 0x7b, 0xf5, 0x0e, 0xf1,
	0x66, 0x05, 0xcb, 0xc6, 0xda, 0xc0, 0x75, 0x96, 0x96, 0x65, 0xcb, 0xb2, 0xb7, 0x83, 0xaf, 0x17,
	0xf0, 0x25, 0xcd, 0x22, 0xef, 0x10, 0xae, 0x9b, 0x49, 0x90, 0x9d, 0x8a, 0x21, 0xcd, 0x8e, 0xdc,
	0xd9, 0x5d, 0x04, 0x33, 0xde, 0x9e, 0xff, 0xf6, 0xdb, 0xaf, 0x8f, 0x2b, 0x6d, 0xb2, 0x4b, 0x4b,
	0xfc, 0x60, 0xa4, 0xfa, 0x49, 0x91, 0xea, 0xf3, 0x7e, 0xd5, 0x9a, 0xc9, 0x7b, 0x84, 0x1b, 0xd3,
	0xc1, 0x92, 0xf6, 0x3c, 0x97, 0xf3, 0x4b, 0x71, 0x6e, 0x2f, 0x81, 0xb4, 0x91, 0xf6, 0x75, 0xa4,
	0x5b, 0x64, 0x67, 0x51, 0x24, 0xa9, 0x33, 0x7c, 0x46, 0x78, 0xf5, 0xff, 0xb1, 0x92, 0x3b, 0xf3,
	0xac, 0x2a, 0x56, 0xe6, 0xdc, 0x5d, 0x0e, 0x6c, 0xa3, 0x3d, 0xd2, 0xd1, 0x1e, 0x90, 0xfb, 0x8b,
	0xa2, 0x31, 0xc3, 0x96, 0xf4, 0xb5, 0xfd, 0x02, 0xde, 0xe8, 0x96, 0xec, 0x3e, 0x39, 0x19, 0xbb,
	0xe8, 0x74, 0xec, 0xa2, 0x9f, 0x63, 0x17, 0x7d, 0x98, 0xb8, 0xb5, 0xd3, 0x89, 0x5b, 0xfb, 0x3e,
	0x71, 0x6b, 0xcf, 0xfd, 0x38, 0x51, 0xfd, 0x22, 0xf4, 0x23, 0x48, 0xe7, 0xa9, 0xbf, 0x32, 0xfa,
	0x6a, 0x94, 0x71, 0x19, 0xd6, 0xf5, 0x1f, 0x77, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x0f,
	0xab, 0x54, 0x38, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// BurnStats returns global burn counters/totals.
	BurnStats(ctx context.Context, in *QueryBurnStatsRequest, opts ...grpc.CallOption) (*QueryBurnStatsResponse, error)
	// AccountBurns returns the total burned by a single account.
	AccountBurns(ctx context.Context, in *QueryAccountBurnsRequest, opts ...grpc.CallOption) (*QueryAccountBurnsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/monochain.burn.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BurnStats(ctx context.Context, in *QueryBurnStatsRequest, opts ...grpc.CallOption) (*QueryBurnStatsResponse, error) {
	out := new(QueryBurnStatsResponse)
	err := c.cc.Invoke(ctx, "/monochain.burn.v1.Query/BurnStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AccountBurns(ctx context.Context, in *QueryAccountBurnsRequest, opts ...grpc.CallOption) (*QueryAccountBurnsResponse, error) {
	out := new(QueryAccountBurnsResponse)
	err := c.cc.Invoke(ctx, "/monochain.burn.v1.Query/AccountBurns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// BurnStats returns global burn counters/totals.
	BurnStats(context.Context, *QueryBurnStatsRequest) (*QueryBurnStatsResponse, error)
	// AccountBurns returns the total burned by a single account.
	AccountBurns(context.Context, *QueryAccountBurnsRequest) (*QueryAccountBurnsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BurnStats(ctx context.Context, req *QueryBurnStatsRequest) (*QueryBurnStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnStats not implemented")
}
func (*UnimplementedQueryServer) AccountBurns(ctx context.Context, req *QueryAccountBurnsRequest) (*QueryAccountBurnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountBurns not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monochain.burn.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BurnStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBurnStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BurnStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monochain.burn.v1.Query/BurnStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BurnStats(ctx, req.(*QueryBurnStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AccountBurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountBurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AccountBurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monochain.burn.v1.Query/AccountBurns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AccountBurns(ctx, req.(*QueryAccountBurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monochain.burn.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BurnStats",
			Handler:    _Query_BurnStats_Handler,
		},
		{
			MethodName: "AccountBurns",
			Handler:    _Query_AccountBurns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monochain/burn/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBurnStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBurnStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBurnStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryBurnStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBurnStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBurnStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalBurned) > 0 {
		i -= len(m.TotalBurned)
		copy(dAtA[i:], m.TotalBurned)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TotalBurned)))
		i--
		dAtA[i] = 0x12
	}
	if m.TotalBurns != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalBurns))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountBurnsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountBurnsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountBurnsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountBurnsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountBurnsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountBurnsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBurnStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryBurnStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalBurns != 0 {
		n += 1 + sovQuery(uint64(m.TotalBurns))
	}
	l = len(m.TotalBurned)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountBurnsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountBurnsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBurnStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBurnStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBurnStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBurnStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBurnStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBurnStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurns", wireType)
			}
			m.TotalBurns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBurns |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBurned = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountBurnsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountBurnsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountBurnsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountBurnsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountBurnsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountBurnsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
