// Code generated by MockGen. DO NOT EDIT.
// Source: x/validator/types/expected_keepers.go
//
// Generated by this command:
//
//	mockgen -source=x/validator/types/expected_keepers.go -package testutil -destination x/validator/testutil/expected_keepers_mocks.go
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	types "github.com/cosmos/cosmos-sdk/types"
	types0 "github.com/cosmos/cosmos-sdk/x/staking/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBurnKeeper is a mock of BurnKeeper interface.
type MockBurnKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockBurnKeeperMockRecorder
	isgomock struct{}
}

// MockBurnKeeperMockRecorder is the mock recorder for MockBurnKeeper.
type MockBurnKeeperMockRecorder struct {
	mock *MockBurnKeeper
}

// NewMockBurnKeeper creates a new mock instance.
func NewMockBurnKeeper(ctrl *gomock.Controller) *MockBurnKeeper {
	mock := &MockBurnKeeper{ctrl: ctrl}
	mock.recorder = &MockBurnKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBurnKeeper) EXPECT() *MockBurnKeeperMockRecorder {
	return m.recorder
}

// BurnFromAccount mocks base method.
func (m *MockBurnKeeper) BurnFromAccount(ctx context.Context, senderAddr types.AccAddress, amount types.Coin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BurnFromAccount", ctx, senderAddr, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// BurnFromAccount indicates an expected call of BurnFromAccount.
func (mr *MockBurnKeeperMockRecorder) BurnFromAccount(ctx, senderAddr, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BurnFromAccount", reflect.TypeOf((*MockBurnKeeper)(nil).BurnFromAccount), ctx, senderAddr, amount)
}

// MockStakingMsgServer is a mock of StakingMsgServer interface.
type MockStakingMsgServer struct {
	ctrl     *gomock.Controller
	recorder *MockStakingMsgServerMockRecorder
	isgomock struct{}
}

// MockStakingMsgServerMockRecorder is the mock recorder for MockStakingMsgServer.
type MockStakingMsgServerMockRecorder struct {
	mock *MockStakingMsgServer
}

// NewMockStakingMsgServer creates a new mock instance.
func NewMockStakingMsgServer(ctrl *gomock.Controller) *MockStakingMsgServer {
	mock := &MockStakingMsgServer{ctrl: ctrl}
	mock.recorder = &MockStakingMsgServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStakingMsgServer) EXPECT() *MockStakingMsgServerMockRecorder {
	return m.recorder
}

// CreateValidator mocks base method.
func (m *MockStakingMsgServer) CreateValidator(arg0 context.Context, arg1 *types0.MsgCreateValidator) (*types0.MsgCreateValidatorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateValidator", arg0, arg1)
	ret0, _ := ret[0].(*types0.MsgCreateValidatorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateValidator indicates an expected call of CreateValidator.
func (mr *MockStakingMsgServerMockRecorder) CreateValidator(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateValidator", reflect.TypeOf((*MockStakingMsgServer)(nil).CreateValidator), arg0, arg1)
}
